select patno,
    to_date('15/'||assessdate3cn, 'DD/MM/YYYY') as assessdate3c,
    systobp3c,
    diastbp3c,
    pulse3c,
    temp3c,
    weight3c,
    height3c,
    bsa3c,
    gcsf3c,
    who3c,
    to_date('15/'||fbcdate3cn, 'DD/MM/YYYY') as fbcdate3c,
    hb3c,
    plts3c,
    wbc3c,
    ancneuphil3c,
    alclympcyt3c,
    to_date('15/'||uedate3cn, 'DD/MM/YYYY') as uedate3c,
    na3c,
    k3c,
    ca3c,
    urea3c,
    urate3c,
    creat3c,
    creatcle3c,
    to_date('15/'||lftdate3cn, 'DD/MM/YYYY') as lftdate3c,
    bili3c,
    alkphos3c,
    alt3c,
    totprot3c,
    albu3c,
    mrdassessf06 
from arctic_v5.end3cycle;
