select patno,
    alive3m,
    to_date('15/'||alivedate3mn, 'DD/MM/YYYY') as alivedate3m,
    progress3m,
    to_date('15/'||assessdate3mn, 'DD/MM/YYYY') as assessdate3m,
    systobp3m,
    diastbp3m,
    pulse3m,
    temp3m,
    weight3m,
    height3m,
    bsa3m,
    gcsf3m,
    who3m,
    ctscan3m,
    to_date('15/'||ctdate3mn, 'DD/MM/YYYY') as ctdate3m,
    ctpleeff3m,
    ctpereff3m,
    ctextra3m,
    thonodinv3m,
    abdnodinv3m,
    pelnodinv3m,
    physlymassess3m,
    to_date('15/'||lymassessdate3mn, 'DD/MM/YYYY') as lymassessdate3m,
    cernodsize3m,
    supnodsize3m,
    axinodsize3m,
    ingnodsize3m,
    livassess3m,
    to_date('15/'||livassessdate3mn, 'DD/MM/YYYY') as livassessdate3m,
    livassesscm3m,
    splenect3m,
    splenectcm3m,
    to_date('15/'||fbcdate3mn, 'DD/MM/YYYY') as fbcdate3m,
    hb3m,
    plts3m,
    wbc3m,
    ancneuphil3m,
    alclympcyt3m,
    iwcll3m,
    mrdassess3m,
    signf08p5,
    signf08p5pb,
    mrdpctf08p5pb,
    to_date('15/'||compdatef08p5n, 'DD/MM/YYYY') as compdatef08p5 
from arctic_v5.m3posttrt;
