select patno,
    chemog,
    chemotype,
    chemocycrec,
    chemocycran,
    chemonotg,
    null as chemonotgoth,
    to_date('15/'||chemocycddaten, 'DD/MM/YYYY') as chemocycddate,
    to_date('15/'||chemocycsdaten, 'DD/MM/YYYY') as chemocycsdate,
    to_date('15/'||chemocycedaten, 'DD/MM/YYYY') as chemocycedate,
    chemomod,
    othtx,
    pcp,
    pcpname,
    null as pcpnameoth,
    pcpnotg,
    null as pcpnotgoth,
    chemocont,
    to_date('15/'||chemoedaten, 'DD/MM/YYYY') as chemoedate,
    chemoereas,
    null as chemoereasoth 
from arctic_v5.treat;
