select patno,
    to_date('15/'||assessdateendn, 'DD/MM/YYYY') as assessdateend,
    systobpend,
    diastbpend,
    pulseend,
    tempend,
    weightend,
    heightend,
    bsaend,
    gcsfend,
    who3end,
    to_date('15/'||fbcdateendn, 'DD/MM/YYYY') as fbcdateend,
    hbend,
    pltsend,
    wbcend,
    ancneuphilend,
    alclympcytend,
    to_date('15/'||uedateendn, 'DD/MM/YYYY') as uedateend,
    naend,
    kend,
    caend,
    ureaend,
    urateend,
    creatend,
    creatcleend,
    to_date('15/'||lftdateendn, 'DD/MM/YYYY') as lftdateend,
    biliend,
    alkphosend,
    altend,
    totprotend,
    albuend,
    to_date('15/'||dctdateendn, 'DD/MM/YYYY') as dctdateend,
    dctend,
    to_date('15/'||retcountdateendn, 'DD/MM/YYYY') as retcountdateend,
    retcountend 
from admire_v5.endtrt;
