select patno,
    null as diagdate,
    null as medcond,
    ctscanb,
    to_date('15/'||ctdatebn, 'DD/MM/YYYY') as ctdateb,
    ctpleeffb,
    ctpereffb,
    ctextrab,
    thonodinvb,
    abdnodinvb,
    pelnodinvb,
    physlympassess,
    to_date('15/'||lympassessdaten, 'DD/MM/YYYY') as lympassessdate,
    cernodsizeb,
    supnodsizeb,
    axinodsizeb,
    ingnodsizeb,
    chestxrayb,
    to_date('15/'||chestxraydatebn, 'DD/MM/YYYY') as chestxraydateb,
    chestxrayintb,
    ecgb,
    to_date('15/'||ecgdatebn, 'DD/MM/YYYY') as ecgdateb,
    ecgintb,
    livassessb,
    to_date('15/'||livassessdatebn, 'DD/MM/YYYY') as livassessdateb,
    livassesscmb,
    splenectb,
    splenectcmb,
    to_date('15/'||binetstagedatebn, 'DD/MM/YYYY') as binetstagedateb,
    binetstageb,
    to_date('15/'||assessdatebn, 'DD/MM/YYYY') as assessdateb,
    systobpb,
    diastbpb,
    pulseb,
    tempb,
    weightb,
    heightb,
    bsab,
    bsymb,
    enemb,
    whob,
    to_date('15/'||fbcdatebn, 'DD/MM/YYYY') as fbcdateb,
    hbb,
    pltsb,
    wbcb,
    ancneuphilb,
    alclympcytb,
    to_date('15/'||uedatebn, 'DD/MM/YYYY') as uedateb,
    nab,
    kb,
    cab,
    ureab,
    urateb,
    creatb,
    creatcleb,
    to_date('15/'||lftdatebn, 'DD/MM/YYYY') as lftdateb,
    bilib,
    alkphosb,
    altb,
    totprotb,
    albub,
    ldhb,
    to_date('15/'||ldhdatebn, 'DD/MM/YYYY') as ldhdateb,
    b2mb,
    to_date('15/'||b2mdatebn, 'DD/MM/YYYY') as b2mdateb,
    dctb,
    to_date('15/'||dctdatebn, 'DD/MM/YYYY') as dctdateb,
    glucoseb,
    to_date('15/'||glucosedatebn, 'DD/MM/YYYY') as glucosedateb,
    retcountb,
    to_date('15/'||retcountdatebn, 'DD/MM/YYYY') as retcountdateb,
    hepbb,
    to_date('15/'||hepbdatebn, 'DD/MM/YYYY') as hepbdateb,
    hepcb,
    to_date('15/'||hepcdatebn, 'DD/MM/YYYY') as hepcdateb,
    hivb,
    to_date('15/'||hivdatebn, 'DD/MM/YYYY') as hivdateb,
    to_date('15/'||ppdatebn, 'DD/MM/YYYY') as ppdateb,
    pptypeb,
    ppconcb,
    sigab,
    siggb,
    sigmb 
from admire_v5.medhist;
