select patno,
    chemog,
    chemotype,
    chemocycrec,
    chemocycran,
    chemonotg,
    chemonotgoth,
    chemocycddate,
    chemocycsdate,
    chemocycedate,
    chemomod,
    othtx,
    pcp,
    pcpname,
    pcpnameoth,
    pcpnotg,
    pcpnotgoth,
    chemocont,
    chemoedate,
    chemoereas,
    chemoereasoth 
from admire_v4.treat;
